import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

// Certificate paths — generated by: mkcert localhost 127.0.0.1
// Run mkcert from the BACKEND folder, then copy certs here too,
// OR point these paths directly at the backend folder certs.
const certDir = path.resolve(__dirname, '..', 'backend')
const certFile = path.join(certDir, 'localhost+1.pem')
const keyFile  = path.join(certDir, 'localhost+1-key.pem')

const httpsConfig = fs.existsSync(certFile) && fs.existsSync(keyFile)
  ? { cert: fs.readFileSync(certFile), key: fs.readFileSync(keyFile) }
  : false  // fall back to HTTP if certs not found

if (httpsConfig) {
  console.log('✅ Vite: HTTPS enabled using mkcert certs from backend/')
} else {
  console.log('⚠  Vite: Running HTTP — run mkcert in backend/ to enable HTTPS')
}

export default defineConfig({
  plugins: [react()],
  server: {
    https: httpsConfig,
    port: 5173,
    host: 'localhost',
  }
})
